# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NYC Shelters, Are We All in This Together?
author: Ceinna Little
logo: logo.png
copyright: 2024

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ceinna/nyc-shelters  # Online location of your book

# Add GitHub buttons to your book


# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true


# get plotly images to load 

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    

